# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.2

#layer definitions
static_layer:
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser
    laser: {topic: scan, sensor_frame: laser_frame, data_type: LaserScan, clearing: true, marking: true, inf_is_valid: true}

inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 3.0
